config/routes.rb
Rails.application.routes.draw do
  root to: "consultas#index"

  resources :consultas do
    get "delete"
  end

  resources :pacientes

  resources :medicos

end

app/models/consulta.rb
class Consulta < ActiveRecord::Base
  belongs_to :medico
  belongs_to :paciente
end

app/models/medico.rb
class Medico < ActiveRecord::Base
  has_many :consultas
  has_many :pacientes, :through => :consultas
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  has_many :consultas
  has_many :pacientes, :through => :consultas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/consultas_controller.rb
class ConsultasController < ApplicationController
  before_action :set_consulta, only: [:show, :edit, :update, :destroy]
  before_action :list_medicos, only: [:new, :edit]
  before_action :list_pacientes, only: [:new, :edit]

  respond_to :html, :js

  # GET /consultas
  # GET /consultas.json
  def index
    @consultas = Consulta.all
  end

  # GET /consultas/1
  # GET /consultas/1.json
  def show
  end

  # GET /consultas/new
  def new
    @consulta = Consulta.new
  end

  # GET /consultas/1/edit
  def edit
  end

  # POST /consultas
  # POST /consultas.json
  def create
    @consultas = Consulta.all
    @consulta = Consulta.create(consulta_params)
  end

  # PATCH/PUT /consultas/1
  # PATCH/PUT /consultas/1.json
  def update
    respond_to do |format|
      if @consulta.update(consulta_params)
        format.html { redirect_to @consulta, notice: 'Consulta was successfully updated.' }
        format.json { render :show, status: :ok, location: @consulta }
      else
        format.html { render :edit }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @consulta = Consulta.find(params[:consulta_id])
  end

  # DESTROY/consultas/1
  # DESTROY/consultas/1.json
  def destroy
    @consultas = Consulta.all
    @consulta = Consulta.find(params[:id])
    @consulta.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consulta
      @consulta = Consulta.find(params[:id])
    end

    def list_medicos
      @medicos = Medico.all.map{ |m| [ m.nome, m.id ] }
    end

    def list_pacientes
      @pacientes = Paciente.all.map{ |p| [ p.nome, p.id ] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consulta_params
      params.require(:consulta).permit(:data, :hora, :medico_id, :paciente_id)
    end
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'Medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nome, :crm, :fone, :email)
    end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nome, :idade, :fone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/consultas/_delete.html.erb
    <div class="modal-header">
    <h3>Exclusão de Consulta</h3>
    </div>
    <div class="modal-body">
    <ul class="errors"></ul>
        Confirma a exclusão da consulta com o Dr. <b><%= @consulta.medico.nome %></b> com o paciente <b><%= @consulta.paciente.nome %>?
    </div>
    <div class="modal-footer">
        <%= link_to "Sim!", consulta_path(@consulta), method: :delete, remote: true, class: "btn btn-danger" %>
        <%= link_to "Não!", "#", class: "btn", data: { dismiss: "modal" } %>
    </div>

app/views/consultas/_form.html.erb
    <%= form_for @consulta, remote: true, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
        <div class="modal-body">
            <ul class="errors"></ul>

            <div class="control-group">
          <%= f.label :data, class:"control-label" %>
                <div class="controls">
                    <%= f.text_field :data, :class => 'datepicker' %>
                </div>
            </div>
            <div class="control-group">
          <%= f.label :hora, class: "control-label" %>
                <div class="controls">
                     <%= f.text_field :hora, :class => 'input-small bootstrap-timepicker' %>
                </div>
            </div>

      <div class="control-group">
            <%= f.label :medico_id, class: "control-label" %>
                <div class="controls">
                    <%= f.select(:medico_id, options_for_select(@medicos)) %>
                </div>
            </div>

      <div class="control-group">
            <%= f.label :paciente_id, class: "control-label" %>
                <div class="controls">
                    <%= f.select(:paciente_id, options_for_select(@pacientes)) %>
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <%= f.submit class: "btn btn-primary" %>
            <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
        </div>
    <% end %>

    <script>
    $(document).ready(function(){
        $('.datepicker').datepicker({ format: 'dd/mm/yyyy',
                                                   orientation: 'auto'
                                                });

        $('.bootstrap-timepicker').timepicker({ minuteStep: 5,
                                                           showInputs: false,
                                                           disableFocus: true
                                                        });

    });
    </script>

app/views/consultas/_index.html.erb
<% @consultas.each do |consulta| %>
      <tr>
        <td><%= consulta.data.strftime("%d/%m/%Y") %></td>
        <td><%= consulta.hora.strftime("%H:%M") %></td>
        <td><%= consulta.medico.nome %></td>
        <td><%= consulta.paciente.nome %></td>
        <td><%= link_to 'Editar', edit_consulta_path(consulta) , remote: true, class: "btn btn-info btn-small"%></td>
        <td><%= link_to 'Remover', consulta_delete_path(consulta), remote: true, class: "btn btn-danger btn-small" %></td>
      </tr>
    <% end %>

app/views/consultas/_new.html.erb
    <div class="modal-header">
      <h3>Nova Consulta</h3>
    </div>
    <%= render "form" %>

app/views/consultas/_save.js.erb
  $("ul.errors").html("")

  <% if @consulta.errors.any? %>
      <% @consulta.errors.full_messages.each do |message| %>
      $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
  <% else %>
      $(".consulta-index").html("<%= escape_javascript(render 'index') %>")
      $("#consulta-modal").modal("hide")
  <% end %>

app/views/consultas/create.js.erb
<%= render "save" %>

app/views/consultas/delete.js.erb
  $("#consulta-modal").html("<%= escape_javascript(render 'delete') %>")
  $("#consulta-modal").modal("show")

app/views/consultas/destroy.js.erb
<%= render "save" %>

app/views/consultas/edit.html.erb
<h1>Editing consulta</h1>

<%= render 'form' %>

<%= link_to 'Show', @consulta %> |
<%= link_to 'Back', consultas_path %>

app/views/consultas/index.html.erb
<div class="container">
      <h1>Consultas</h1>
        <div class="well">
            <%= link_to "Nova", new_consulta_path, remote: true, class: "btn btn-success" %>
        </div>
        <div class="new-consulta"></div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                  <th>Data</th>
                  <th>Hora</th>
                  <th>Médico</th>
                  <th>Paciente</th>
                  <th colspan="3">Ação</th>
                </tr>
            </thead>

            <tbody class="consulta-index">
                <%= render "index" %>
            </tbody>
        </table>
</div>
<div id="consulta-modal" class="modal hide fade"></div>

app/views/consultas/new.js.erb
    $("#consulta-modal").html("<%= escape_javascript(render 'new') %>")
    $("#consulta-modal").modal("show")

app/views/consultas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @consulta.data %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @consulta.hora %>
</p>

<p>
  <strong>Medico:</strong>
  <%= @consulta.medico %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= @consulta.paciente %>
</p>

<%= link_to 'Edit', edit_consulta_path(@consulta) %> |
<%= link_to 'Back', consultas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospital</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medicos/_form.html.erb
<%= form_for(@medico) do |f| %>
  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :crm %><br>
    <%= f.number_field :crm %>
  </div>
  <div class="field">
    <%= f.label :fone %><br>
    <%= f.text_field :fone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render 'form' %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

app/views/medicos/index.html.erb
<h1>Listing medicos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Crm</th>
      <th>Fone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= medico.nome %></td>
        <td><%= medico.crm %></td>
        <td><%= medico.fone %></td>
        <td><%= medico.email %></td>
        <td><%= link_to 'Show', medico %></td>
        <td><%= link_to 'Edit', edit_medico_path(medico) %></td>
        <td><%= link_to 'Destroy', medico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medico', new_medico_path %>

app/views/medicos/new.html.erb
<h1>New medico</h1>

<%= render 'form' %>

<%= link_to 'Back', medicos_path %>

app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @medico.nome %>
</p>

<p>
  <strong>Crm:</strong>
  <%= @medico.crm %>
</p>

<p>
  <strong>Fone:</strong>
  <%= @medico.fone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @medico.email %>
</p>

<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>

app/views/pacientes/_form.html.erb
<%= form_for(@paciente) do |f| %>
  <% if @paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% @paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :fone %><br>
    <%= f.text_field :fone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editing paciente</h1>

<%= render 'form' %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

app/views/pacientes/index.html.erb
<h1>Listing pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Fone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><%= paciente.idade %></td>
        <td><%= paciente.fone %></td>
        <td><%= paciente.email %></td>
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>New paciente</h1>

<%= render 'form' %>

<%= link_to 'Back', pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @paciente.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @paciente.idade %>
</p>

<p>
  <strong>Fone:</strong>
  <%= @paciente.fone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @paciente.email %>
</p>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>